@WebApiDemo_HostAddress = http://localhost:5296

GET {{WebApiDemo_HostAddress}}/weatherforecast/GetWeatherForecast
Accept: application/json

###

### ClientController tests

# Create a client
POST {{WebApiDemo_HostAddress}}/client
Content-Type: application/json

{
  "clientName": "Test Client",
  "address": "123 Test St"
}

###

# Get all clients
GET {{WebApiDemo_HostAddress}}/client
Accept: application/json

###


